export const commonStyles = {
  container: {
    padding: "1rem",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "2rem",
    flexWrap: "wrap",
    gap: "1rem",
  },
  headerLeft: {
    flex: 1,
  },
  title: {
    fontSize: "1.875rem",
    fontWeight: "600",
    color: "#111827",
    margin: "0 0 0.5rem 0",
  },
  subtitle: {
    fontSize: "0.95rem",
    color: "#6b7280",
    margin: "0",
  },
  addButton: {
    backgroundColor: "#4f46e5",
    color: "white",
    border: "none",
    padding: "0.75rem 1.25rem",
    borderRadius: "10px",
    fontSize: "0.95rem",
    fontWeight: "600",
    cursor: "pointer",
    transition: "background 0.2s ease",
  },
  searchContainer: {
    position: "relative",
    marginBottom: "2rem",
  },
  searchInput: {
    width: "100%",
    boxSizing: "border-box",
    padding: "0.85rem 1rem 0.85rem 3rem",
    fontSize: "0.95rem",
    border: "1px solid #d1d5db",
    borderRadius: "10px",
  },
  searchIcon: {
    position: "absolute",
    left: "1rem",
    top: "50%",
    transform: "translateY(-50%)",
    color: "#9ca3af",
  },
  sectionTitle: {
    fontSize: "1.25rem",
    fontWeight: "650",
    color: "#111827",
    margin: "0 0 1rem 0",
  },
  sectionSubtitle: {
    fontSize: "0.95rem",
    color: "#6b7280",
    margin: "0 0 1rem 0",
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(15, 23, 42, 0.45)",
    zIndex: 50,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "1rem",
  },
  modal: {
    width: "100%",
    maxWidth: "560px",
    backgroundColor: "#fff",
    borderRadius: "18px",
    boxShadow: "0 30px 60px rgba(15, 23, 42, 0.16)",
    overflow: "hidden",
  },
  modalHeader: {
    padding: "1.5rem",
    borderBottom: "1px solid #e5e7eb",
  },
  modalTitle: {
    margin: "0 0 0.25rem 0",
    fontSize: "1.35rem",
    fontWeight: 700,
    color: "#111827",
  },
  modalSubtitle: {
    margin: 0,
    color: "#6b7280",
    fontSize: "0.95rem",
  },
  form: {
    padding: "1.5rem",
    display: "grid",
    gap: "1rem",
  },
  formGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
  },
  label: {
    fontSize: "0.95rem",
    fontWeight: 600,
    color: "#111827",
  },
  input: {
    width: "100%",
    padding: "0.85rem 1rem",
    borderRadius: "10px",
    border: "1px solid #d1d5db",
    fontSize: "0.95rem",
    color: "#111827",
  },
  modalActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "0.75rem",
    marginTop: "1rem",
  },
  cancelButton: {
    backgroundColor: "#f3f4f6",
    color: "#374151",
    border: "1px solid #d1d5db",
    padding: "0.75rem 1.25rem",
    borderRadius: "10px",
    cursor: "pointer",
    fontWeight: 600,
  },
  submitButton: {
    backgroundColor: "#111827",
    color: "white",
    border: "none",
    padding: "0.75rem 1.5rem",
    borderRadius: "10px",
    cursor: "pointer",
    fontWeight: 700,
    minWidth: "130px",
  },
  paginationBar: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: "1rem",
    marginTop: "1.5rem",
  },
  paginationButton: {
    backgroundColor: "#fff",
    border: "1px solid #d1d5db",
    padding: "0.65rem 1rem",
    borderRadius: "8px",
    cursor: "pointer",
    color: "#111827",
    fontWeight: 600,
  },
  paginationButtonDisabled: {
    opacity: 0.45,
    cursor: "not-allowed",
  },
  paginationText: {
    fontSize: "0.95rem",
    color: "#475569",
    fontWeight: 600,
  },
};
